using System.Text.Json;
using System.Text.RegularExpressions;
using System.Xml;
using System.Xml.Linq;

namespace MasterWoW.UIStudio.Core;

public sealed class TbcClientCache
{
    private const string CacheFormat="6";
    private static readonly JsonSerializerOptions Json = new() { WriteIndented = true, PropertyNamingPolicy = JsonNamingPolicy.CamelCase, PropertyNameCaseInsensitive = true, Converters = { new System.Text.Json.Serialization.JsonStringEnumConverter() } };
    public async Task<IReadOnlyDictionary<string,TextureAsset>> LoadTextureLookupAsync(TbcClientProfile profile,CancellationToken ct=default){var path=Path.Combine(profile.CacheRoot,"TBC243","textures.json");if(!File.Exists(path))return new Dictionary<string,TextureAsset>(StringComparer.OrdinalIgnoreCase);try{await using var stream=File.OpenRead(path);var assets=await JsonSerializer.DeserializeAsync<List<TextureAsset>>(stream,Json,ct)??new();return assets.ToDictionary(x=>x.File.DiskPath,StringComparer.OrdinalIgnoreCase);}catch{return new Dictionary<string,TextureAsset>(StringComparer.OrdinalIgnoreCase);}}
    public async Task<TbcClientIndex?> LoadAsync(TbcClientProfile profile,CancellationToken ct=default)
    {
        var root=Path.Combine(profile.CacheRoot,"TBC243");if(!Directory.Exists(root)||!File.Exists(Path.Combine(root,"cache-format.txt"))||!string.Equals((await File.ReadAllTextAsync(Path.Combine(root,"cache-format.txt"),ct)).Trim(),CacheFormat,StringComparison.Ordinal))return null;
        try
        {
            var index=new TbcClientIndex{Profile=profile,Files=await Read<List<InterfaceFileRecord>>("interface-files.json")??new(),Textures=await Read<List<TextureAsset>>("textures.json")??new(),Templates=await Read<List<XmlTemplateDefinition>>("templates.json")??new(),Globals=await Read<List<GlobalRecord>>("lua-globals.json")??new(),ApiUsage=await Read<List<ApiUsageRecord>>("lua-api-usage.json")??new(),Events=await Read<List<EventUsageRecord>>("events.json")??new(),Dependencies=await Read<List<InterfaceDependency>>("dependencies.json")??new(),Diagnostics=await Read<List<ScanDiagnostic>>("scan-diagnostics.json")??new(),Metadata=await Read<ScanMetadata>("scan-metadata.json")};
            return index.Files.Count==0?null:index;
        }
        catch{return null;}
        async Task<T?> Read<T>(string name){var path=Path.Combine(root,name);if(!File.Exists(path))return default;await using var stream=File.OpenRead(path);return await JsonSerializer.DeserializeAsync<T>(stream,Json,ct);}
    }
    public async Task SaveAsync(TbcClientIndex index, CancellationToken ct = default)
    {
        var root=Path.Combine(index.Profile.CacheRoot,"TBC243");Directory.CreateDirectory(root);
        await Write("interface-files.json",index.Files);await Write("textures.json",index.Textures);await Write("templates.json",index.Templates);await Write("lua-globals.json",index.Globals);await Write("lua-api-usage.json",index.ApiUsage);await Write("events.json",index.Events);await Write("fonts.json",index.Files.Where(x=>x.Kind==InterfaceFileKind.Font));await Write("dependencies.json",index.Dependencies);await Write("scan-diagnostics.json",index.Diagnostics);await Write("scan-metadata.json",index.Metadata);await File.WriteAllTextAsync(Path.Combine(root,"cache-format.txt"),CacheFormat,ct);
        async Task Write<T>(string name,T value){await using var stream=File.Create(Path.Combine(root,name));await JsonSerializer.SerializeAsync(stream,value,Json,ct);}
    }
}

public sealed class InterfaceScanner
{
    private static readonly Regex MethodCall=new(@"(?m)(?:\b[A-Za-z_]\w*|\))\s*:\s*(?<name>[A-Za-z_]\w*)\s*\(",RegexOptions.Compiled);
    private static readonly Regex GlobalCall=new(@"(?m)(?<![.:\w])(?<name>[A-Z][A-Za-z0-9_]*)\s*\(",RegexOptions.Compiled);
    private static readonly Regex RegisterEvent=new(@"RegisterEvent\s*\(\s*[\""'](?<event>[A-Z][A-Z0-9_]+)[\""']",RegexOptions.Compiled);
    private static readonly Regex GlobalFunction=new(@"(?m)^\s*function\s+(?<name>[A-Za-z_]\w*)\s*\(",RegexOptions.Compiled);
    private static readonly HashSet<string> FrameElements=new(StringComparer.OrdinalIgnoreCase){"Frame","Button","CheckButton","EditBox","ScrollFrame","Slider","StatusBar","MessageFrame","ScrollingMessageFrame","Model","PlayerModel","DressUpModel","TabardModel","Minimap","GameTooltip","Cooldown"};
    private readonly BlpDecoder _blp=new(); private readonly TgaDecoder _tga=new();

    public async Task<TbcClientIndex> ScanAsync(TbcClientProfile profile,ScanMode mode=ScanMode.Incremental,IProgress<ScanProgress>? progress=null,CancellationToken ct=default)
    {
        if(!Directory.Exists(profile.InterfaceRoot))throw new DirectoryNotFoundException(profile.InterfaceRoot);var start=DateTimeOffset.UtcNow;var index=new TbcClientIndex{Profile=profile};var cache=new TbcClientCache();var oldTextures=mode==ScanMode.Incremental?await cache.LoadTextureLookupAsync(profile,ct):new Dictionary<string,TextureAsset>(StringComparer.OrdinalIgnoreCase);
        var diskFiles=await Task.Run(()=>Enumerate(profile).Distinct(StringComparer.OrdinalIgnoreCase).ToList(),ct);var total=diskFiles.Count;var n=0;
        foreach(var path in diskFiles){ct.ThrowIfCancellationRequested();var record=CreateRecord(profile,path);index.Files.Add(record);if(record.Kind is InterfaceFileKind.Blp or InterfaceFileKind.Tga){TextureMetadata? metadata=null;if(oldTextures.TryGetValue(record.DiskPath,out var old)&&old.File.Size==record.Size&&old.File.LastWriteUtc==record.LastWriteUtc)metadata=old.Metadata;else try{using var stream=File.Open(path,FileMode.Open,FileAccess.Read,FileShare.ReadWrite);metadata=record.Kind==InterfaceFileKind.Blp?_blp.ReadMetadata(stream):_tga.ReadMetadata(stream);}catch(Exception ex){var knownPlaceholder=record.Kind==InterfaceFileKind.Blp&&Path.GetFileName(record.DiskPath).Equals("pixelfix1.blp",StringComparison.OrdinalIgnoreCase)&&ex.Message.StartsWith("Unsupported BLP magic",StringComparison.Ordinal);if(!knownPlaceholder)index.Diagnostics.Add(new("Warning","Texture metadata",ex.Message,record.RelativePath));}index.Textures.Add(new(record,metadata,Array.Empty<string>()));}if(++n%250==0)progress?.Report(new("Indexing files",n,total,record.RelativePath));}
        var xmlFiles=index.Files.Where(x=>x.Kind==InterfaceFileKind.Xml).ToList();n=0;foreach(var file in xmlFiles){ct.ThrowIfCancellationRequested();try{ParseXml(file,index);}catch(Exception ex){index.Diagnostics.Add(new("Warning","XML parse",ex.Message,file.RelativePath));}progress?.Report(new("Parsing XML",++n,xmlFiles.Count,file.RelativePath));}
        ResolveInheritance(index);
        var luaFiles=index.Files.Where(x=>x.Kind==InterfaceFileKind.Lua).ToList();var api=new Dictionary<string,List<SourceOccurrence>>(StringComparer.Ordinal);var events=new Dictionary<string,List<SourceOccurrence>>(StringComparer.Ordinal);var globals=new Dictionary<string,List<string>>(StringComparer.Ordinal);n=0;
        foreach(var file in luaFiles){ct.ThrowIfCancellationRequested();try{var source=await File.ReadAllTextAsync(file.DiskPath,ct);ScanLua(file,source,api,events,globals);}catch(Exception ex){index.Diagnostics.Add(new("Warning","Lua scan",ex.Message,file.RelativePath));}progress?.Report(new("Scanning Lua",++n,luaFiles.Count,file.RelativePath));}
        index.ApiUsage.AddRange(api.Select(x=>new ApiUsageRecord(x.Key,x.Value.Count,x.Value.Select(y=>y.File).Distinct(StringComparer.OrdinalIgnoreCase).OrderBy(y=>y).ToList(),x.Value)).OrderByDescending(x=>x.UsageCount));
        index.Events.AddRange(events.Select(x=>new EventUsageRecord(x.Key,x.Value.Count,x.Value.Select(y=>y.File).Distinct(StringComparer.OrdinalIgnoreCase).OrderBy(y=>y).ToList())).OrderByDescending(x=>x.UsageCount));
        index.Globals.AddRange(globals.Select(x=>new GlobalRecord(x.Key,"Function",EnvironmentFor(x.Value[0]),x.Value.Distinct(StringComparer.OrdinalIgnoreCase).ToList())).OrderBy(x=>x.Name));
        var blp=index.Files.Count(x=>x.Kind==InterfaceFileKind.Blp);var tga=index.Files.Count(x=>x.Kind==InterfaceFileKind.Tga);index.Metadata=new(profile.Name,profile.TargetVersion,profile.InterfaceRoot,start,DateTimeOffset.UtcNow,mode,luaFiles.Count,xmlFiles.Count,blp,tga,index.Files.Count(x=>x.Kind==InterfaceFileKind.Font),index.Templates.Count,index.Templates.Count(x=>!x.Virtual),index.ApiUsage.Count,index.Events.Count,0,index.Diagnostics.Count(x=>x.Severity=="Warning"),index.Diagnostics.Count(x=>x.Severity=="Error"));
        await cache.SaveAsync(index,ct);progress?.Report(new("Complete",total,total,null));return index;
    }
    private static IEnumerable<string> Enumerate(TbcClientProfile p){var extensions=new HashSet<string>(StringComparer.OrdinalIgnoreCase){".lua",".xml",".blp",".tga",".ttf",".otf",".png",".jpg",".jpeg",".dds"};foreach(var f in Directory.EnumerateFiles(p.InterfaceRoot,"*",SearchOption.AllDirectories))if(extensions.Contains(Path.GetExtension(f)))yield return f;if(p.AssetRoot is {Length:>0} asset&&Directory.Exists(asset)&&!Path.GetFullPath(asset).StartsWith(Path.GetFullPath(p.InterfaceRoot),StringComparison.OrdinalIgnoreCase))foreach(var f in Directory.EnumerateFiles(asset,"*",SearchOption.AllDirectories))if(extensions.Contains(Path.GetExtension(f)))yield return f;}
    private static InterfaceFileRecord CreateRecord(TbcClientProfile p,string path){var ext=Path.GetExtension(path);var kind=ext.ToLowerInvariant() switch{".lua"=>InterfaceFileKind.Lua,".xml"=>InterfaceFileKind.Xml,".blp"=>InterfaceFileKind.Blp,".tga"=>InterfaceFileKind.Tga,".ttf" or ".otf"=>InterfaceFileKind.Font,".png"=>InterfaceFileKind.Png,".jpg" or ".jpeg"=>InterfaceFileKind.Jpeg,".dds"=>InterfaceFileKind.Dds,_=>InterfaceFileKind.Other};var root=Path.GetFullPath(p.InterfaceRoot);var full=Path.GetFullPath(path);string relative,wow;if(full.StartsWith(root,StringComparison.OrdinalIgnoreCase)){relative=Path.GetRelativePath(root,full);wow="Interface\\"+relative.Replace('/','\\');}else{var assetRoot=Path.GetFullPath(p.AssetRoot!);relative=Path.GetRelativePath(assetRoot,full);wow=relative.Replace('/','\\');}var info=new FileInfo(full);return new(full,relative,wow,kind,EnvironmentFor(relative),info.Length,info.LastWriteTimeUtc,ext);}
    private static ClientEnvironment EnvironmentFor(string relative)=>relative.StartsWith("GlueXML",StringComparison.OrdinalIgnoreCase)||relative.StartsWith("GLUES",StringComparison.OrdinalIgnoreCase)?ClientEnvironment.Glue:relative.StartsWith("FrameXML",StringComparison.OrdinalIgnoreCase)?ClientEnvironment.InGame:ClientEnvironment.Shared;
    private static void ParseXml(InterfaceFileRecord file,TbcClientIndex index)
    {
        var settings=new XmlReaderSettings{DtdProcessing=DtdProcessing.Prohibit,XmlResolver=null};using var reader=XmlReader.Create(file.DiskPath,settings);var doc=XDocument.Load(reader,LoadOptions.SetLineInfo);var order=0;
        foreach(var node in doc.Descendants())
        {
            var local=node.Name.LocalName;if(local is "Include" or "Script"&&node.Attribute("file") is { } include)index.Dependencies.Add(new(file.RelativePath,include.Value.Replace('/','\\'),local,order++));if(!FrameElements.Contains(local))continue;var name=(string?)node.Attribute("name");if(string.IsNullOrWhiteSpace(name))continue;
            var parentNode=node.Ancestors().FirstOrDefault(x=>FrameElements.Contains(x.Name.LocalName));var parentName=(string?)parentNode?.Attribute("name");var virtualValue=string.Equals((string?)node.Attribute("virtual"),"true",StringComparison.OrdinalIgnoreCase);var inherits=((string?)node.Attribute("inherits")??"").Split(new[]{',',' '},StringSplitOptions.RemoveEmptyEntries|StringSplitOptions.TrimEntries);var size=node.Elements().FirstOrDefault(x=>x.Name.LocalName=="Size");double? width=Dimension(size,"x");double? height=Dimension(size,"y");var anchors=ReadAnchors(node);
            var regions=node.Descendants().Where(x=>x.Name.LocalName is "Texture" or "FontString").Where(x=>ReferenceEquals(x.Ancestors().FirstOrDefault(a=>FrameElements.Contains(a.Name.LocalName)),node)).Select(x=>{var regionSize=x.Elements().FirstOrDefault(e=>e.Name.LocalName=="Size");var tex=x.Elements().FirstOrDefault(e=>e.Name.LocalName=="TexCoords");IReadOnlyList<double>? coords=tex is null?null:new[]{Number(tex.Attribute("left"))??0,Number(tex.Attribute("right"))??1,Number(tex.Attribute("top"))??0,Number(tex.Attribute("bottom"))??1};return new XmlRegionDefinition((string?)x.Attribute("name")??"",x.Name.LocalName,(string?)x.Parent?.Attribute("level"),(string?)x.Attribute("file"),(string?)x.Attribute("text"),Dimension(regionSize,"x"),Dimension(regionSize,"y"),ReadAnchors(x),Bool(x.Attribute("hidden"))==true,Bool(x.Attribute("setAllPoints"))==true,(string?)x.Attribute("inherits"),coords);}).ToList();
            var scripts=node.Elements().FirstOrDefault(x=>x.Name.LocalName=="Scripts")?.Elements().ToDictionary(x=>x.Name.LocalName,x=>x.Value.Trim(),StringComparer.OrdinalIgnoreCase)??new Dictionary<string,string>();var children=node.Descendants().Where(x=>FrameElements.Contains(x.Name.LocalName)&&ReferenceEquals(x.Ancestors().FirstOrDefault(a=>FrameElements.Contains(a.Name.LocalName)),node)).Select(x=>(string?)x.Attribute("name")??x.Name.LocalName).ToList();var backdrop=node.Elements().FirstOrDefault(x=>x.Name.LocalName=="Backdrop");var normal=node.Elements().FirstOrDefault(x=>x.Name.LocalName=="NormalTexture");index.Templates.Add(new(name,local,virtualValue,inherits,file.Environment,file.RelativePath,width,height,anchors,regions,scripts,children,Array.Empty<string>(),parentName,(string?)backdrop?.Attribute("bgFile"),(string?)backdrop?.Attribute("edgeFile"),(string?)normal?.Attribute("file"),Bool(node.Attribute("hidden")),Bool(node.Attribute("setAllPoints"))==true,(string?)node.Attribute("text"),(string?)node.Attribute("parent")));
        }
        static List<XmlAnchorDefinition> ReadAnchors(XElement element)=>element.Elements().FirstOrDefault(x=>x.Name.LocalName=="Anchors")?.Elements().Where(x=>x.Name.LocalName=="Anchor").Select(a=>{var offset=a.Elements().FirstOrDefault(x=>x.Name.LocalName=="Offset");return new XmlAnchorDefinition((string?)a.Attribute("point")??"CENTER",(string?)a.Attribute("relativeTo"),(string?)a.Attribute("relativePoint"),Dimension(offset,"x")??0,Dimension(offset,"y")??0);}).ToList()??new();
        static double? Dimension(XElement? container,string axis)=>Number(container?.Attribute(axis))??Number(container?.Elements().FirstOrDefault()?.Attribute(axis));
        static double? Number(XAttribute? a)=>double.TryParse(a?.Value,System.Globalization.NumberStyles.Float,System.Globalization.CultureInfo.InvariantCulture,out var v)?v:null;
        static bool? Bool(XAttribute? a)=>a is null?null:string.Equals(a.Value,"true",StringComparison.OrdinalIgnoreCase)||a.Value=="1";
    }
    private static void ResolveInheritance(TbcClientIndex index){var byName=index.Templates.GroupBy(x=>x.Name,StringComparer.OrdinalIgnoreCase).ToDictionary(x=>x.Key,x=>x.First(),StringComparer.OrdinalIgnoreCase);for(var i=0;i<index.Templates.Count;i++){var item=index.Templates[i];var resolved=new List<string>();var seen=new HashSet<string>(StringComparer.OrdinalIgnoreCase);void Visit(string name){if(!seen.Add(name))return;if(byName.TryGetValue(name,out var parent)){foreach(var ancestor in parent.Inherits)Visit(ancestor);resolved.Add(name);}}foreach(var parent in item.Inherits)Visit(parent);index.Templates[i]=item with{ResolvedInheritance=resolved};}}
    private static void ScanLua(InterfaceFileRecord file,string source,Dictionary<string,List<SourceOccurrence>> api,Dictionary<string,List<SourceOccurrence>> events,Dictionary<string,List<string>> globals){Add(MethodCall);Add(GlobalCall);foreach(Match m in RegisterEvent.Matches(source))Occurrence(events,m.Groups["event"].Value,m);foreach(Match m in GlobalFunction.Matches(source)){var name=m.Groups["name"].Value;if(!globals.TryGetValue(name,out var files))globals[name]=files=new();files.Add(file.RelativePath);}void Add(Regex regex){foreach(Match m in regex.Matches(source))Occurrence(api,m.Groups["name"].Value,m);}void Occurrence(Dictionary<string,List<SourceOccurrence>> target,string name,Match m){if(!target.TryGetValue(name,out var list))target[name]=list=new();var line=1+source.Take(m.Index).Count(c=>c=='\n');var start=Math.Max(0,source.LastIndexOf('\n',Math.Max(0,m.Index-1))+1);var end=source.IndexOf('\n',m.Index);if(end<0)end=source.Length;list.Add(new(file.RelativePath,line,source[start..end].Trim()));}}
}
