namespace MasterWoW.UIStudio.Core;

public sealed class XmlTemplateInstantiator
{
    public WowDocument Instantiate(TbcClientIndex index, string templateName, double screenWidth = 1280, double screenHeight = 720)
    {
        var byName=index.Templates.GroupBy(x=>x.Name,StringComparer.OrdinalIgnoreCase).ToDictionary(x=>x.Key,x=>x.First(),StringComparer.OrdinalIgnoreCase);
        if(!byName.TryGetValue(templateName,out var template))throw new KeyNotFoundException(templateName);var document=new WowDocument(screenWidth,screenHeight);var type=Enum.TryParse<WowObjectType>(template.Type,true,out var parsed)?parsed:WowObjectType.Frame;var instanceName="Preview"+template.Name;var frame=new WowUiObject(instanceName,type,document.Root){Width=template.Width??240,Height=template.Height??80};document.ByName[frame.Name]=frame;ApplyTemplate(index,templateName,frame,document);
        return document;
    }

    public bool ApplyTemplate(TbcClientIndex index,string templateName,WowUiObject target,WowDocument document)
    {
        var byName=index.Templates.GroupBy(x=>x.Name,StringComparer.OrdinalIgnoreCase).ToDictionary(x=>x.Key,x=>x.First(),StringComparer.OrdinalIgnoreCase);
        if(!byName.TryGetValue(templateName,out var template))return false;Apply(template,target,new HashSet<string>(StringComparer.OrdinalIgnoreCase)); return true;
        void Apply(XmlTemplateDefinition definition,WowUiObject item,HashSet<string> stack){if(!stack.Add(definition.Name))return;foreach(var parentName in definition.ResolvedInheritance)if(byName.TryGetValue(parentName,out var parent))Apply(parent,item,stack);ApplyOwn(definition,item);stack.Remove(definition.Name);}
        void ApplyOwn(XmlTemplateDefinition definition,WowUiObject item)
        {
            if(definition.Width.HasValue)item.Width=definition.Width.Value;if(definition.Height.HasValue)item.Height=definition.Height.Value;if(definition.SetAllPoints){item.Anchors.Clear();item.Anchors.Add(new("TOPLEFT",item.Parent?.Name??"UIParent","TOPLEFT",0,0));item.Anchors.Add(new("BOTTOMRIGHT",item.Parent?.Name??"UIParent","BOTTOMRIGHT",0,0));}else if(definition.Anchors.Count>0){item.Anchors.Clear();foreach(var a in definition.Anchors)item.Anchors.Add(ToAnchor(a,item.Name,item.Parent?.Name??"UIParent"));}if(definition.Hidden.HasValue)item.Shown=!definition.Hidden.Value;if(definition.Text is not null)item.Text=definition.Text;if(item.TemplateName?.Contains("TabButtonTemplate",StringComparison.OrdinalIgnoreCase)==true&&!string.IsNullOrWhiteSpace(item.Text))item.Width=Math.Max(48,item.Text.Length*7+30);if(!string.IsNullOrWhiteSpace(definition.BackdropBackground))item.BackdropBackground=definition.BackdropBackground;if(!string.IsNullOrWhiteSpace(definition.BackdropEdge))item.BackdropEdge=definition.BackdropEdge;if(!string.IsNullOrWhiteSpace(definition.NormalTexture))item.TexturePath=definition.NormalTexture;
            foreach(var region in definition.Regions){var rt=region.Type.Equals("Texture",StringComparison.OrdinalIgnoreCase)?WowObjectType.Texture:WowObjectType.FontString;var name=Expand(string.IsNullOrWhiteSpace(region.Name)?$"$parent{region.Type}{item.Children.Count+1}":region.Name,item.Name);if(document.ByName.ContainsKey(name))continue;var intrinsicWidth=rt==WowObjectType.FontString?Math.Max(8,(region.Text?.Length??1)*7):100;var intrinsicHeight=rt==WowObjectType.FontString?14:40;var child=new WowUiObject(name,rt,item){TexturePath=region.File,Text=region.Text,Width=region.Width??intrinsicWidth,Height=region.Height??intrinsicHeight,Shown=!region.Hidden,TemplateName=region.Inherits,TextureCoordinates=region.TexCoords?.ToArray()??new[]{0d,1d,0d,1d}};var fillParent=rt==WowObjectType.Texture&&!region.Width.HasValue&&!region.Height.HasValue&&region.Anchors is not {Count:>0};if(region.SetAllPoints||fillParent){child.Anchors.Add(new("TOPLEFT",item.Name,"TOPLEFT",0,0));child.Anchors.Add(new("BOTTOMRIGHT",item.Name,"BOTTOMRIGHT",0,0));}else if(region.Anchors is {Count:>0})foreach(var a in region.Anchors)child.Anchors.Add(ToAnchor(a,item.Name,item.Name));document.ByName[name]=child;}
            foreach(var childKey in definition.Children){var childDefinition=index.Templates.FirstOrDefault(x=>x.Name.Equals(childKey,StringComparison.OrdinalIgnoreCase)&&x.DefinedIn.Equals(definition.DefinedIn,StringComparison.OrdinalIgnoreCase)&&x.ParentName?.Equals(definition.Name,StringComparison.OrdinalIgnoreCase)==true)??index.Templates.FirstOrDefault(x=>x.Name.Equals(childKey,StringComparison.OrdinalIgnoreCase)&&x.ParentName?.Equals(definition.Name,StringComparison.OrdinalIgnoreCase)==true);if(childDefinition is null)continue;var name=Expand(childDefinition.Name,item.Name);if(document.ByName.ContainsKey(name))continue;var type=Enum.TryParse<WowObjectType>(childDefinition.Type,true,out var parsed)?parsed:WowObjectType.Frame;var child=new WowUiObject(name,type,item){TemplateName=childDefinition.Inherits.FirstOrDefault()};document.ByName[name]=child;Apply(childDefinition,child,new HashSet<string>(StringComparer.OrdinalIgnoreCase));}
            foreach(var script in definition.Scripts.Keys)item.Scripts.Add(script);
        }
        WowAnchor ToAnchor(XmlAnchorDefinition anchor,string instanceName,string defaultRelative){var relative=string.IsNullOrWhiteSpace(anchor.RelativeTo)?defaultRelative:Expand(anchor.RelativeTo,instanceName);return new(anchor.Point,relative,anchor.RelativePoint??anchor.Point,anchor.X,anchor.Y);}
        static string Expand(string value,string parentName)=>value.Replace("$parent",parentName,StringComparison.OrdinalIgnoreCase);
    }
}
