using System;
using System.Linq;
using System.Globalization;
using System.Collections.Generic;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using MasterWoW.UIStudio.Core;
using Microsoft.Win32;

namespace MasterWoW.UIStudio.App;
public partial class MainWindow : Window
{
 private readonly MainViewModel _vm = new(); private readonly ClientSettingsService _settings=new(); private readonly TextureCache _textureCache=new(); private readonly Dictionary<string,ImageBrush> _textureBrushes=new(StringComparer.OrdinalIgnoreCase); private readonly Dictionary<string,FontFamily> _fontFamilies=new(StringComparer.OrdinalIgnoreCase); private readonly HashSet<string> _textureLoads=new(StringComparer.OrdinalIgnoreCase); private CancellationTokenSource? _scanCancellation; private TbcClientProfile? _profile; private StudioPreferences _preferences=new(); private bool _syncing; private Point? _dragStart; private Point? _dragElementStart; private WowUiObject? _dragObject; private ResizeSnapshot? _resizeStart;
 private sealed record ResizeHandle(WowUiObject Item,bool Left,bool Top);
 private sealed record ResizeSnapshot(double Width,double Height,double X,double Y);
 public MainWindow() { InitializeComponent(); DataContext = _vm; Editor.Text = _vm.Source; _vm.PreviewChanged += (_, _) => RefreshAll(); _profile=_settings.Load();_preferences=_settings.LoadPreferences();ApplyWorkspaceVisibility(); RefreshAll(); Loaded+=InitializeAsync; }
 private async void InitializeAsync(object sender,RoutedEventArgs e){Loaded-=InitializeAsync;if(_profile is not null&&Directory.Exists(_profile.InterfaceRoot)){ScanStatus.Text="Loading saved Interface cache…";var cached=await new TbcClientCache().LoadAsync(_profile);if(cached is not null){_vm.SetClientIndex(cached);ScanStatus.Text=$"Interface cache loaded: {cached.Files.Count:N0} files; refreshing new assets…";_ = RunScanAsync(ScanMode.Incremental,false);}else{ScanStatus.Text="Saved Interface folder found; scanning…";await RunScanAsync(ScanMode.Incremental,false);}}OpenCommandLineFileAsync(sender,e);}
 private async void OpenCommandLineFileAsync(object sender,RoutedEventArgs e){Loaded-=OpenCommandLineFileAsync;var args=Environment.GetCommandLineArgs();if(args.Length<2||!File.Exists(args[1]))return;try{await _vm.OpenAsync(Path.GetFullPath(args[1]));}catch(Exception ex){_vm.Document.Diagnostics.Add(new(DiagnosticSeverity.Error,"Open file",ex.Message));RefreshAll();}}
 private void RefreshAll() { _syncing = true; if (Editor.Text != _vm.Source) Editor.Text = _vm.Source; _syncing = false; PreviewHost.Width = PreviewCanvas.Width = _vm.PreviewWidth; PreviewHost.Height = PreviewCanvas.Height = _vm.PreviewHeight; BuildTree(); RenderPreview(); Diagnostics.ItemsSource = _vm.Document.Diagnostics.Select(d => $"{d.Severity.ToString().ToUpperInvariant()}  [{d.Category}] {d.Message}").ToList(); ApiCalls.ItemsSource = _vm.Document.ApiCalls.ToList(); AioHandlers.ItemsSource=_vm.Document.AioHandlers.ToList(); ShowProperties(); }
 private void BuildTree() { FrameTree.Items.Clear(); FrameTree.Items.Add(Node(_vm.Root)); static TreeViewItem Node(WowUiObject item) { var n = new TreeViewItem { Header = $"{item.Name}  [{item.Type}]", Tag = item, IsExpanded = item.Type == WowObjectType.UIParent }; foreach (var c in item.Children) n.Items.Add(Node(c)); return n; } }
 private void RenderPreview()
 {
  PreviewCanvas.Children.Clear(); foreach (var c in Ordered(_vm.Root.Children)) Render(c);
  void Render(WowUiObject item) { if (!item.Shown) return; var rect=new WowLayoutEngine().Resolve(item,_vm.Document); var p=new Point(rect.Left*_vm.UiScale,rect.Top*_vm.UiScale); var selected=item==_vm.Selected; var decorative=item.Type is WowObjectType.FontString or WowObjectType.Texture; var b = new Border { Width = Math.Max(1, rect.Width * _vm.UiScale), Height = Math.Max(1, rect.Height * _vm.UiScale), Opacity = item.Alpha*(item.Enabled?1:.55), Tag = item, BorderThickness = new Thickness(selected?2:decorative?0:1), BorderBrush = selected?Brushes.Gold:BorderFor(item), Background = BrushFor(item), ToolTip = $"{item.Name}\n{item.Type}\n{rect.Width:0.#} × {rect.Height:0.#}\n{item.FrameStrata}:{item.FrameLevel}" }; var displayText=_vm.DisplayText(item.Text);if(item.Type!=WowObjectType.Texture&&!string.IsNullOrEmpty(displayText))b.Child = new TextBlock { Text = displayText, Foreground = ColorBrush(item.TextColor), FontFamily=FontFor(item), FontSize=Math.Max(8,item.FontSize*_vm.UiScale), HorizontalAlignment = Horizontal(item.HorizontalJustification), VerticalAlignment = Vertical(item.VerticalJustification), TextAlignment=TextAlignmentFor(item.HorizontalJustification), TextWrapping = TextWrapping.Wrap, IsHitTestVisible = false, Margin=new Thickness(item.TextInsets.Left,item.TextInsets.Top,item.TextInsets.Right,item.TextInsets.Bottom) }; b.MouseLeftButtonDown += Object_MouseLeftButtonDown;b.MouseLeftButtonUp+=Canvas_MouseLeftButtonUp;Canvas.SetLeft(b,p.X); Canvas.SetTop(b,p.Y); PreviewCanvas.Children.Add(b); if (selected && item != _vm.Root) AddResizeHandles(item,b); foreach (var c in Ordered(item.Children)) Render(c); }
  static IEnumerable<WowUiObject> Ordered(IEnumerable<WowUiObject> items)=>items.OrderBy(x=>StrataOrder(x.FrameStrata)).ThenBy(x=>x.FrameLevel);
  static int StrataOrder(string value)=>value.ToUpperInvariant() switch{"BACKGROUND"=>0,"LOW"=>1,"MEDIUM"=>2,"HIGH"=>3,"DIALOG"=>4,"FULLSCREEN"=>5,"FULLSCREEN_DIALOG"=>6,"TOOLTIP"=>7,_=>2};
 }
 private void AddResizeHandles(WowUiObject item,Border border)
 {
  foreach(var handle in new[]{new ResizeHandle(item,true,true),new ResizeHandle(item,false,true),new ResizeHandle(item,true,false),new ResizeHandle(item,false,false)}){var t=new Thumb{Width=14,Height=14,Background=Brushes.Gold,BorderBrush=Brushes.Black,BorderThickness=new Thickness(1),Cursor=handle.Left==handle.Top?Cursors.SizeNWSE:Cursors.SizeNESW,Tag=handle};t.DragStarted+=Resize_DragStarted;t.DragDelta+=Resize_DragDelta;t.DragCompleted+=Resize_DragCompleted;Canvas.SetLeft(t,Canvas.GetLeft(border)+(handle.Left?-7:border.Width-7));Canvas.SetTop(t,Canvas.GetTop(border)+(handle.Top?-7:border.Height-7));PreviewCanvas.Children.Add(t);}
 }
 private Brush BrushFor(WowUiObject i){var close=i.TemplateName?.Contains("UIPanelCloseButton",StringComparison.OrdinalIgnoreCase)==true;var path=i.Type==WowObjectType.Texture||close||i.Type is WowObjectType.Button or WowObjectType.CheckButton?i.TexturePath:i.BackdropBackground;var normalized=string.IsNullOrWhiteSpace(path)?"":AssetResolver.Normalize(path);if(normalized.Contains("WHITE8X8",StringComparison.OrdinalIgnoreCase))return ColorBrush(i.Type==WowObjectType.Texture?i.VertexColor:i.BackdropColor);if(!string.IsNullOrWhiteSpace(path)&&_vm.ClientIndex is not null){var coords=i.TextureCoordinates;var crop=$"{coords[0]:0.######},{coords[1]:0.######},{coords[2]:0.######},{coords[3]:0.######}";var key=normalized+"|"+crop;if(_textureBrushes.TryGetValue(key,out var loaded))return loaded;StartTextureLoad(key,path,coords);if(_vm.Document.ReadOnlyClientPreview)return new SolidColorBrush(Color.FromArgb(24,0,0,0));}if(i.Type is WowObjectType.FontString)return Brushes.Transparent;if(close)return Brushes.Transparent;if(_vm.Document.ReadOnlyClientPreview&&i.Type is WowObjectType.Button or WowObjectType.CheckButton or WowObjectType.Texture)return Brushes.Transparent;if(i.Type is WowObjectType.Button or WowObjectType.CheckButton&&i.TemplateName?.Contains("UIPanel",StringComparison.OrdinalIgnoreCase)==true)return new LinearGradientBrush(Color.FromRgb(128,9,4),Color.FromRgb(52,2,1),90);if(!string.IsNullOrWhiteSpace(i.BackdropBackground))return ColorBrush(i.BackdropColor);return i.Type switch { WowObjectType.Button or WowObjectType.CheckButton => new SolidColorBrush(Color.FromRgb(72,18,14)), WowObjectType.EditBox => new SolidColorBrush(Color.FromRgb(12,12,14)), WowObjectType.StatusBar => new SolidColorBrush(Color.FromRgb(35,110,55)), WowObjectType.Texture => ColorBrush(i.VertexColor), _ => Brushes.Transparent };}
 private FontFamily FontFor(WowUiObject item){var requested=item.FontPath??"Fonts\\FRIZQT__.TTF";if(_fontFamilies.TryGetValue(requested,out var cached))return cached;if(_vm.ClientIndex is not null){var file=_vm.ClientIndex.Files.FirstOrDefault(x=>x.Kind==InterfaceFileKind.Font&&(AssetResolver.Normalize(x.WowPath).Equals(AssetResolver.Normalize(requested),StringComparison.OrdinalIgnoreCase)||Path.GetFileName(x.DiskPath).Equals(Path.GetFileName(requested),StringComparison.OrdinalIgnoreCase)));if(file is not null)try{var uri=new Uri(file.DiskPath);var glyph=new GlyphTypeface(uri);var family=glyph.Win32FamilyNames.Values.FirstOrDefault()??"Friz Quadrata TT";return _fontFamilies[requested]=new FontFamily(new Uri(Path.GetDirectoryName(file.DiskPath)+Path.DirectorySeparatorChar),"./#"+family);}catch{}}return _fontFamilies[requested]=new FontFamily("Friz Quadrata TT, Georgia");}
 private static Brush BorderFor(WowUiObject i)=>!string.IsNullOrWhiteSpace(i.BackdropEdge)?ColorBrush(i.BackdropBorderColor):new SolidColorBrush(Color.FromArgb(150,76,91,108));
 private static SolidColorBrush ColorBrush((double R,double G,double B,double A) c)=>new(Color.FromArgb(Byte(c.A),Byte(c.R),Byte(c.G),Byte(c.B)));
 private static byte Byte(double value)=>(byte)Math.Round(Math.Clamp(value,0,1)*255);
 private static HorizontalAlignment Horizontal(string value)=>value=="LEFT"?HorizontalAlignment.Left:value=="RIGHT"?HorizontalAlignment.Right:HorizontalAlignment.Center;
 private static VerticalAlignment Vertical(string value)=>value=="TOP"?VerticalAlignment.Top:value=="BOTTOM"?VerticalAlignment.Bottom:VerticalAlignment.Center;
 private static TextAlignment TextAlignmentFor(string value)=>value=="LEFT"?TextAlignment.Left:value=="RIGHT"?TextAlignment.Right:TextAlignment.Center;
 private async void StartTextureLoad(string key,string requested,double[] coords){if(!_textureLoads.Add(key)||_vm.ClientIndex is null)return;try{var resolved=new AssetResolver(_vm.ClientIndex.Files).Resolve(requested);var diskPath=resolved.File?.DiskPath;if(diskPath is null&&_profile is not null)diskPath=AssetResolver.ResolveFromInterfaceFolder(_profile.InterfaceRoot,requested);if(diskPath is null){if(!_vm.Document.Diagnostics.Any(x=>x.Category=="Missing texture"&&x.Message.Contains(requested,StringComparison.OrdinalIgnoreCase)))_vm.Document.Diagnostics.Add(new(DiagnosticSeverity.Warning,"Missing texture",$"{requested}; attempted: {string.Join(", ",resolved.AttemptedPaths)}"));return;}var texture=await _textureCache.GetOrDecodeAsync(diskPath,DecodeTextureAsync);var width=Math.Max(0.0001,coords[1]-coords[0]);var height=Math.Max(0.0001,coords[3]-coords[2]);var brush=new ImageBrush(WpfTextureFactory.Create(texture)){Stretch=Stretch.Fill,ViewboxUnits=BrushMappingMode.RelativeToBoundingBox,Viewbox=new Rect(coords[0],coords[2],width,height)};brush.Freeze();_textureBrushes[key]=brush;RenderPreview();}catch(Exception ex){_vm.Document.Diagnostics.Add(new(DiagnosticSeverity.Warning,"Texture decode",$"{requested}: {ex.Message}"));}finally{_textureLoads.Remove(key);}}
 private static Task<DecodedTexture> DecodeTextureAsync(string path,CancellationToken ct)=>Task.Run(()=>{using var stream=File.Open(path,FileMode.Open,FileAccess.Read,FileShare.ReadWrite);ITextureDecoder decoder=path.EndsWith(".blp",StringComparison.OrdinalIgnoreCase)?new BlpDecoder():new TgaDecoder();return decoder.Decode(stream);},ct);
 private Point Position(WowUiObject item) { var parent=item.Parent??_vm.Root; var rel=_vm.Document.ByName.TryGetValue(item.Anchor.RelativeTo,out var f)?f:parent; var rp=rel==_vm.Root?new Point():Position(rel); var own=AnchorOffset(item.Anchor.Point,item.Width,item.Height); var target=AnchorOffset(item.Anchor.RelativePoint,rel.Width,rel.Height); return new((rp.X+target.X-own.X+item.Anchor.X)*_vm.UiScale,(rp.Y+target.Y-own.Y-item.Anchor.Y)*_vm.UiScale); }
 private static Point AnchorOffset(string a,double w,double h) { a=a.ToUpperInvariant(); return new(a.Contains("LEFT")?0:a.Contains("RIGHT")?w:w/2,a.Contains("TOP")?0:a.Contains("BOTTOM")?h:h/2); }
 private void Object_MouseLeftButtonDown(object s,MouseButtonEventArgs e) { var element=(FrameworkElement)s;var i=(WowUiObject)element.Tag; _vm.Selected=i;_dragObject=i;_dragStart=e.GetPosition(PreviewCanvas);_dragElementStart=new(Canvas.GetLeft(element),Canvas.GetTop(element));element.CaptureMouse();ShowProperties();NavigateToSource(i);e.Handled=true; }
 private void Canvas_MouseMove(object s,MouseEventArgs e) { if(_dragStart is null||_dragElementStart is null||_dragObject is null||e.LeftButton!=MouseButtonState.Pressed)return;var current=e.GetPosition(PreviewCanvas);var element=PreviewCanvas.Children.OfType<FrameworkElement>().FirstOrDefault(x=>ReferenceEquals(x.Tag,_dragObject)&&x is Border);if(element is null)return;Canvas.SetLeft(element,_dragElementStart.Value.X+current.X-_dragStart.Value.X);Canvas.SetTop(element,_dragElementStart.Value.Y+current.Y-_dragStart.Value.Y); }
 private async void Canvas_MouseLeftButtonUp(object s,MouseButtonEventArgs e) { if (_dragStart is null||_dragObject is null) return; var end=e.GetPosition(PreviewCanvas); var dx=(end.X-_dragStart.Value.X)/_vm.UiScale; var dy=-(end.Y-_dragStart.Value.Y)/_vm.UiScale; Mouse.Capture(null); var i=_dragObject; _dragStart=null;_dragElementStart=null;_dragObject=null;if(Math.Abs(dx)>.01||Math.Abs(dy)>.01)ConfirmGeometry(i,null,null,i.Anchor.X+dx,i.Anchor.Y+dy);else if(i.Type is WowObjectType.Button or WowObjectType.CheckButton&&i.Scripts.Contains("OnClick")){var requestCount=_vm.Document.AioRequests.Count;await _vm.InvokeFrameScriptAsync(i,"OnClick");if(_vm.Document.AioRequests.Count>requestCount)await ReplayPreviewRequestAsync(_vm.Document.AioRequests[^1]);}else RenderPreview(); }
 private async Task ReplayPreviewRequestAsync(AioRequestRegistration request){var tab=request.Handler.ToUpperInvariant() switch{"REQUESTTAB"=>request.Arguments.FirstOrDefault() as string,"REQUESTHOME"=>"home","REQUESTCHALLENGES"=>Convert.ToInt32(request.Arguments.FirstOrDefault()??1)==2?"weekly":"daily","REQUESTLOOT"=>"loot","REQUESTLFG"=>"lfg","REQUESTLEADERBOARD"=>"leaderboards",_=>null};if(string.IsNullOrWhiteSpace(tab))return;JsonObject payload;try{payload=JsonNode.Parse(string.IsNullOrWhiteSpace(AioPayloadJson.Text)?"{}":AioPayloadJson.Text) as JsonObject??new JsonObject();}catch{payload=new JsonObject();}payload["activeTab"]=tab;if(tab is "daily" or "weekly")payload["tabData"]=new JsonObject{{"title",tab=="daily"?"Daily Challenges":"Weekly Challenges"}};else payload["tabData"]=new JsonObject();AioPayloadJson.Text=payload.ToJsonString(new JsonSerializerOptions{WriteIndented=true});var handler=_vm.Document.AioHandlers.FirstOrDefault(x=>x.Module.Equals(request.Module,StringComparison.OrdinalIgnoreCase)&&x.Handler.Equals("ShowWindow",StringComparison.OrdinalIgnoreCase));if(handler is null)return;using var json=JsonDocument.Parse(AioPayloadJson.Text);await _vm.InvokeAioHandlerAsync(handler,null,json.RootElement.Clone());}
 private void Resize_DragStarted(object s,DragStartedEventArgs e){var i=((ResizeHandle)((Thumb)s).Tag).Item;_resizeStart=new(i.Width,i.Height,i.Anchor.X,i.Anchor.Y);}
 private void Resize_DragDelta(object s,DragDeltaEventArgs e)
 {
  var handle=(ResizeHandle)((Thumb)s).Tag;var i=handle.Item;var dx=e.HorizontalChange/_vm.UiScale;var dy=e.VerticalChange/_vm.UiScale;var oldWidth=i.Width;var oldHeight=i.Height;i.Width=Math.Max(1,i.Width+(handle.Left?-dx:dx));i.Height=Math.Max(1,i.Height+(handle.Top?-dy:dy));dx=handle.Left?oldWidth-i.Width:i.Width-oldWidth;dy=handle.Top?oldHeight-i.Height:i.Height-oldHeight;var point=i.Anchor.Point.ToUpperInvariant();var x=i.Anchor.X;var y=i.Anchor.Y;if(handle.Left)x+=point.Contains("LEFT")?dx:point.Contains("RIGHT")?0:dx/2;else x+=point.Contains("RIGHT")?dx:point.Contains("LEFT")?0:dx/2;if(handle.Top)y-=point.Contains("TOP")?dy:point.Contains("BOTTOM")?0:dy/2;else y-=point.Contains("BOTTOM")?dy:point.Contains("TOP")?0:dy/2;i.Anchor=i.Anchor with{X=x,Y=y};var border=PreviewCanvas.Children.OfType<Border>().FirstOrDefault(x=>ReferenceEquals(x.Tag,i));if(border is not null){var rect=new WowLayoutEngine().Resolve(i,_vm.Document);border.Width=Math.Max(1,rect.Width*_vm.UiScale);border.Height=Math.Max(1,rect.Height*_vm.UiScale);Canvas.SetLeft(border,rect.Left*_vm.UiScale);Canvas.SetTop(border,rect.Top*_vm.UiScale);foreach(var thumb in PreviewCanvas.Children.OfType<Thumb>().Where(x=>x.Tag is ResizeHandle h&&ReferenceEquals(h.Item,i))){var h=(ResizeHandle)thumb.Tag;Canvas.SetLeft(thumb,Canvas.GetLeft(border)+(h.Left?-7:border.Width-7));Canvas.SetTop(thumb,Canvas.GetTop(border)+(h.Top?-7:border.Height-7));}}ShowProperties();
 }
 private void Resize_DragCompleted(object s,DragCompletedEventArgs e){var i=((ResizeHandle)((Thumb)s).Tag).Item;if(_resizeStart is not { } before)return;var width=i.Width;var height=i.Height;var x=i.Anchor.X;var y=i.Anchor.Y;i.Width=before.Width;i.Height=before.Height;i.Anchor=i.Anchor with{X=before.X,Y=before.Y};_resizeStart=null;ConfirmGeometry(i,width,height,Math.Abs(x-before.X)>.001?x:null,Math.Abs(y-before.Y)>.001?y:null);}
 private void FrameTree_SelectedItemChanged(object s,RoutedPropertyChangedEventArgs<object> e) { if(e.NewValue is TreeViewItem { Tag: WowUiObject i }) { _vm.Selected=i; ShowProperties();NavigateToSource(i);RenderPreview(); } }
 private void NavigateToSource(WowUiObject item){var span=item.Sources.Values.OrderBy(x=>x.Line).FirstOrDefault();var offset=span?.ValueStart??-1;var length=span?.ValueLength??0;if(offset<0&&!string.IsNullOrWhiteSpace(item.Text)){var quoted="\""+item.Text+"\"";offset=_vm.Source.IndexOf(quoted,StringComparison.Ordinal);length=quoted.Length;}if(offset<0&&!item.Name.StartsWith("anonymous#",StringComparison.Ordinal)){offset=_vm.Source.IndexOf(item.Name,StringComparison.Ordinal);length=item.Name.Length;}if(offset<0)return;Editor.CaretOffset=offset;Editor.Select(offset,Math.Max(0,length));Editor.ScrollToLine(1+_vm.Source.Take(offset).Count(c=>c=='\n'));}
 private void ConfirmGeometry(WowUiObject item,double? width,double? height,double? x,double? y){var requested=new[]{("Width",width),("Height",height),("X",x),("Y",y)}.Where(v=>v.Item2.HasValue).ToList();var mapped=requested.Where(v=>item.Sources.ContainsKey(v.Item1)).ToList();if(mapped.Count!=requested.Count){if(_preferences.AutoAcceptDesignerChanges){_vm.SaveDesignerGeometry(item,width,height,x,y);return;}if(MessageBox.Show("This control is generated by shared Lua code, so Studio cannot safely identify one Lua literal to change.\n\nSave a STUDIO-ONLY preview override? WoW will not read this override and the Lua addon will remain unchanged.","Preview-only layout",MessageBoxButton.YesNo,MessageBoxImage.Warning)==MessageBoxResult.Yes)_vm.SaveDesignerGeometry(item,width,height,x,y);else RefreshAll();return;}if(_preferences.AutoAcceptDesignerChanges){_vm.PatchGeometry(item,width,height,x,y);return;}var summary=string.Join("\n",mapped.Select(v=>$"{v.Item1}: {item.Sources[v.Item1].OriginalText} → {v.Item2:0.###}"));if(MessageBox.Show($"Apply this change directly to the Lua file?\n\n{summary}\n\nThis change will affect WoW after the edited file is deployed. A .mwstudio.bak backup will be kept.","Confirm Lua change",MessageBoxButton.YesNo,MessageBoxImage.Question)!=MessageBoxResult.Yes){RefreshAll();return;}_vm.PatchGeometry(item,width,height,x,y);}
 private void ShowProperties() { if(_vm.Selected is not { } i)return; WidthBox.Text=i.Width.ToString("0.###",CultureInfo.InvariantCulture); HeightBox.Text=i.Height.ToString("0.###",CultureInfo.InvariantCulture); Xbox.Text=i.Anchor.X.ToString("0.###",CultureInfo.InvariantCulture); Ybox.Text=i.Anchor.Y.ToString("0.###",CultureInfo.InvariantCulture); }
 private void ApplyProperties_Click(object s,RoutedEventArgs e) { if(_vm.Selected is not { } i)return; if(Try(WidthBox.Text,out var w)&&Try(HeightBox.Text,out var h)&&Try(Xbox.Text,out var x)&&Try(Ybox.Text,out var y))ConfirmGeometry(i,Different(w,i.Width)?w:null,Different(h,i.Height)?h:null,Different(x,i.Anchor.X)?x:null,Different(y,i.Anchor.Y)?y:null); static bool Try(string s,out double v)=>double.TryParse(s,NumberStyles.Float,CultureInfo.InvariantCulture,out v);static bool Different(double a,double b)=>Math.Abs(a-b)>.001; }
 private void Editor_TextChanged(object? s,EventArgs e){if(!_syncing)_vm.Source=Editor.Text;} private async void Reload_Click(object s,RoutedEventArgs e)=>await _vm.ReloadAsync();
 private async void Open_Click(object s,RoutedEventArgs e){var d=new OpenFileDialog{Filter="Lua/XML/TOC|*.lua;*.xml;*.toc|All files|*.*"};if(d.ShowDialog()==true)await _vm.OpenAsync(d.FileName);} private void Save_Click(object s,RoutedEventArgs e){try{_vm.Save();ShowSaveResult();}catch{SaveAs_Click(s,e);}} private void SaveAs_Click(object s,RoutedEventArgs e){var d=new SaveFileDialog{Filter="Lua addon (*.lua)|*.lua",DefaultExt=".lua"};if(d.ShowDialog()==true){_vm.SaveAs(d.FileName);ShowSaveResult();}}
 private void ShowSaveResult(){if(_vm.PendingDesignerOverrideCount==0)return;MessageBox.Show($"The Lua file was saved.\n\n{_vm.PendingDesignerOverrideCount} Studio-only layout override(s) were NOT written to Lua because those generated controls do not have a safe source mapping. They remain in:\n\n{_vm.DesignerLayoutPath}\n\nDo not delete that file unless you want to discard the preview layout. Use Edit > Discard Studio-only layout overrides to return to the Lua layout.","Lua saved; preview overrides remain",MessageBoxButton.OK,MessageBoxImage.Warning);}
 private void DiscardDesignerOverrides_Click(object sender,RoutedEventArgs e){if(_vm.PendingDesignerOverrideCount==0){MessageBox.Show("There are no Studio-only layout overrides for this file.","Designer layout",MessageBoxButton.OK,MessageBoxImage.Information);return;}if(MessageBox.Show($"Discard {_vm.PendingDesignerOverrideCount} preview-only layout override(s)?\n\nThis deletes:\n{_vm.DesignerLayoutPath}\n\nThe Lua file is not changed.","Discard preview overrides",MessageBoxButton.YesNo,MessageBoxImage.Warning)==MessageBoxResult.Yes)_vm.DiscardDesignerGeometry();}
 private void Undo_Click(object s,RoutedEventArgs e)=>_vm.Undo(); private void Redo_Click(object s,RoutedEventArgs e)=>_vm.Redo(); private void Window_KeyDown(object s,KeyEventArgs e){if(e.Key==Key.R&&Keyboard.Modifiers.HasFlag(ModifierKeys.Control)){_vm.Reload();e.Handled=true;}else if(e.Key==Key.F11){TogglePreviewOnly();e.Handled=true;}}
 private void ToggleBottomPanels_Click(object sender,RoutedEventArgs e)=>SetPreferences(_preferences with{ShowBottomPanels=ShowBottomPanelsMenu.IsChecked});
 private void TogglePropertiesPanel_Click(object sender,RoutedEventArgs e)=>SetPreferences(_preferences with{ShowPropertiesPanel=ShowPropertiesMenu.IsChecked});
 private void PreviewOnly_Click(object sender,RoutedEventArgs e){var previewOnly=PreviewOnlyMenu.IsChecked;SetPreferences(_preferences with{ShowBottomPanels=!previewOnly,ShowPropertiesPanel=!previewOnly});}
 private void AutoAcceptEdits_Click(object sender,RoutedEventArgs e)=>SetPreferences(_preferences with{AutoAcceptDesignerChanges=AutoAcceptEditsMenu.IsChecked});
 private void TogglePreviewOnly(){var previewOnly=_preferences.ShowBottomPanels||_preferences.ShowPropertiesPanel;SetPreferences(_preferences with{ShowBottomPanels=!previewOnly,ShowPropertiesPanel=!previewOnly});}
 private void SetPreferences(StudioPreferences preferences){_preferences=preferences;ApplyWorkspaceVisibility();_settings.SavePreferences(_preferences);}
 private void ApplyWorkspaceVisibility(){EditorSplitterRow.Height=_preferences.ShowBottomPanels?new GridLength(5):new GridLength(0);EditorRow.Height=_preferences.ShowBottomPanels?new GridLength(2,GridUnitType.Star):new GridLength(0);BottomSplitterRow.Height=_preferences.ShowBottomPanels?new GridLength(5):new GridLength(0);BottomPanelRow.Height=_preferences.ShowBottomPanels?new GridLength(175):new GridLength(0);PropertiesSplitterColumn.Width=_preferences.ShowPropertiesPanel?new GridLength(5):new GridLength(0);PropertiesColumn.Width=_preferences.ShowPropertiesPanel?new GridLength(280):new GridLength(0);ShowBottomPanelsMenu.IsChecked=_preferences.ShowBottomPanels;ShowPropertiesMenu.IsChecked=_preferences.ShowPropertiesPanel;PreviewOnlyMenu.IsChecked=!_preferences.ShowBottomPanels&&!_preferences.ShowPropertiesPanel;AutoAcceptEditsMenu.IsChecked=_preferences.AutoAcceptDesignerChanges;}
 private void Resolution_Changed(object s,SelectionChangedEventArgs e){if(!IsLoaded||Resolution.SelectedItem is not ComboBoxItem c)return;var p=c.Content.ToString()!.Split('x');_vm.PreviewWidth=double.Parse(p[0]);_vm.PreviewHeight=double.Parse(p[1]);_vm.Reload();} private void Scale_Changed(object s,SelectionChangedEventArgs e){if(!IsLoaded||Scale.SelectedItem is not ComboBoxItem c)return;_vm.UiScale=double.Parse(c.Content.ToString()!,CultureInfo.InvariantCulture);_vm.Reload();}
 private void Background_Click(object s,RoutedEventArgs e){var d=new OpenFileDialog{Filter="Images|*.png;*.jpg;*.jpeg;*.bmp"};if(d.ShowDialog()==true){BackgroundImage.Source=new BitmapImage(new Uri(d.FileName));_vm.BackgroundPath=d.FileName;}}
 private async void SetInterfaceRoot_Click(object sender,RoutedEventArgs e){using var dialog=new System.Windows.Forms.FolderBrowserDialog{Description="Select the extracted TBC Interface directory",UseDescriptionForTitle=true,ShowNewFolderButton=false,SelectedPath=_profile?.InterfaceRoot??""};if(dialog.ShowDialog()!=System.Windows.Forms.DialogResult.OK)return;var selected=Path.GetFullPath(dialog.SelectedPath);if(!Directory.Exists(selected)){MessageBox.Show("The selected directory does not exist.");return;}var cache=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"MasterWoW.UIStudio","Cache");var parent=Directory.GetParent(selected)?.FullName;_profile=new TbcClientProfile("MasterWoW TBC 2.4.3","2.4.3.8606",selected,cache,parent);_settings.Save(_profile);ScanStatus.Text="Interface root configured. Scanning…";await RunScanAsync(ScanMode.Incremental);}
 private async void ScanInterface_Click(object sender,RoutedEventArgs e)=>await RunScanAsync(ScanMode.Incremental);
 private async void RebuildCache_Click(object sender,RoutedEventArgs e)=>await RunScanAsync(ScanMode.FullRebuild);
 private async Task RunScanAsync(ScanMode mode,bool showReport=true){if(_profile is null){SetInterfaceRoot_Click(this,new RoutedEventArgs());if(_profile is null)return;}_scanCancellation?.Cancel();_scanCancellation=new CancellationTokenSource();ScanProgress.Visibility=Visibility.Visible;ScanProgress.IsIndeterminate=false;ScanProgress.Minimum=0;ScanStatus.Text="Starting scan…";var progress=new Progress<ScanProgress>(p=>{ScanStatus.Text=$"{p.Phase}: {p.CurrentFile}";if(p.Total.HasValue){ScanProgress.Maximum=p.Total.Value;ScanProgress.Value=p.Processed;}else ScanProgress.IsIndeterminate=true;});try{var index=await new InterfaceScanner().ScanAsync(_profile,mode,progress,_scanCancellation.Token);_vm.SetClientIndex(index);ScanStatus.Text=$"Scan complete: {index.Files.Count:N0} files";if(showReport)new ScanReportWindow(index){Owner=this}.Show();}catch(OperationCanceledException){ScanStatus.Text="Scan canceled";}catch(Exception ex){MessageBox.Show(ex.Message,"TBC client scan failed",MessageBoxButton.OK,MessageBoxImage.Error);ScanStatus.Text="Scan failed";}finally{ScanProgress.Visibility=Visibility.Collapsed;}}
 private void AssetBrowser_Click(object sender,RoutedEventArgs e){if(_vm.ClientIndex is null){MessageBox.Show("Scan a TBC Interface root first.");return;}var window=new AssetBrowserWindow(_vm.ClientIndex){Owner=this};window.UseRequested+=(_,asset)=>{if(_vm.Selected is { } item)_vm.ApplyRuntimeTexture(item,asset.File.WowPath);};window.Show();}
 private void TemplateExplorer_Click(object sender,RoutedEventArgs e){if(_vm.ClientIndex is null){MessageBox.Show("Scan a TBC Interface root first.");return;}var window=new TemplateExplorerWindow(_vm.ClientIndex){Owner=this};window.PreviewRequested+=(_,template)=>_vm.PreviewTemplate(template.Name);window.Show();}
 private void ScanReport_Click(object sender,RoutedEventArgs e){if(_vm.ClientIndex is null){MessageBox.Show("Scan a TBC Interface root first.");return;}new ScanReportWindow(_vm.ClientIndex){Owner=this}.Show();}
 private async void InvokeAio_Click(object sender,RoutedEventArgs e)
 {
  if(AioHandlers.SelectedItem is not AioHandlerRegistration handler)return;
  var button=sender as Button;if(button is not null)button.IsEnabled=false;
  try{using var json=JsonDocument.Parse(string.IsNullOrWhiteSpace(AioPayloadJson.Text)?"{}":AioPayloadJson.Text);await _vm.InvokeAioHandlerAsync(handler,null,json.RootElement.Clone());}
  catch(Exception ex){_vm.Document.Diagnostics.Add(new(DiagnosticSeverity.Error,"AIO handler",ex.Message));RefreshAll();}
  finally{if(button is not null)button.IsEnabled=true;}
 }
 private void ApiExplorer_Click(object sender,RoutedEventArgs e)=>new ApiExplorerWindow{Owner=this}.Show();
}
