<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MasterWoW.UIStudio.Core\MasterWoW.UIStudio.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AvalonEdit" Version="6.3.1.120" />
    <PackageReference Include="MoonSharp" Version="2.0.0" />
  </ItemGroup>
  <ItemGroup><Content Include="..\Data\**\*"><Link>Data\%(RecursiveDir)%(Filename)%(Extension)</Link><CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory></Content></ItemGroup>
  <ItemGroup><Content Include="..\Data\DeveloperKit\APIwithoutaddons.txt"><Link>Data\DeveloperKit\APIwithoutaddons.txt</Link><CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory></Content></ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

</Project>
